raw_data = './data/dataset/'
mini_data = './data/dataset_mini_challenge'
processed_data = './data/processed/'
final_data = './data/final/'
areas = ['brazil', 'france']
types = ['train', 'eval']
crs = 'epsg:4326'

[bbox]
brazil = [-44.5, -21.5, -39.5, -17.5]
france = [-3.0, 40.0, 8.0, 49.0]

